// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class AuthPacket : Record
    {
        private int type;
        private string scheme;
        private byte[] auth;
        public AuthPacket() { }
        public AuthPacket(int type, string scheme, byte[] auth)
        {
            this.type = type;
            this.scheme = scheme;
            this.auth = auth;
        }
        public int get_Type() { return type; }
        internal void set_Type(int m_) { type = m_; }

        public string getScheme() { return scheme; }
        internal void setScheme(string m_) { scheme = m_; }

        public byte[] getAuth() { return auth; }
        internal void setAuth(byte[] m_) { auth = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(type, "type");
            a_.writeString(scheme, "scheme");
            a_.writeBuffer(auth, "auth");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            type = a_.readInt("type");
            scheme = a_.readString("scheme");
            auth = a_.readBuffer("auth");
        }
    }
}
