// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class CheckVersionRequest : Record
    {
        private string path;
        private int version;
        public CheckVersionRequest() { }
        public CheckVersionRequest(string path, int version)
        {
            this.path = path;
            this.version = version;
        }
        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        public int getVersion() { return version; }
        internal void setVersion(int m_) { version = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeString(path, "path");
            a_.writeInt(version, "version");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            path = a_.readString("path");
            version = a_.readInt("version");
        }
    }
}
