// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class ConnectResponse : Record
    {
        private int protocolVersion;
        private int timeOut;
        private long sessionId;
        private byte[] passwd;
        public ConnectResponse() { }
        public ConnectResponse(int protocolVersion, int timeOut, long sessionId, byte[] passwd)
        {
            this.protocolVersion = protocolVersion;
            this.timeOut = timeOut;
            this.sessionId = sessionId;
            this.passwd = passwd;
        }
        public int getProtocolVersion() { return protocolVersion; }
        internal void setProtocolVersion(int m_) { protocolVersion = m_; }

        public int getTimeOut() { return timeOut; }
        internal void setTimeOut(int m_) { timeOut = m_; }

        public long getSessionId() { return sessionId; }
        internal void setSessionId(long m_) { sessionId = m_; }

        public byte[] getPasswd() { return passwd; }
        internal void setPasswd(byte[] m_) { passwd = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(protocolVersion, "protocolVersion");
            a_.writeInt(timeOut, "timeOut");
            a_.writeLong(sessionId, "sessionId");
            a_.writeBuffer(passwd, "passwd");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            protocolVersion = a_.readInt("protocolVersion");
            timeOut = a_.readInt("timeOut");
            sessionId = a_.readLong("sessionId");
            passwd = a_.readBuffer("passwd");
        }
    }
}
