// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class CreateRequest : Record
    {
        private string path;
        private byte[] data;
        private List<org.apache.zookeeper.data.ACL> acl;
        private int flags;
        public CreateRequest() { }
        public CreateRequest(string path, byte[] data, List<org.apache.zookeeper.data.ACL> acl, int flags)
        {
            this.path = path;
            this.data = data;
            this.acl = acl;
            this.flags = flags;
        }
        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        public byte[] getData() { return data; }
        internal void setData(byte[] m_) { data = m_; }

        public List<org.apache.zookeeper.data.ACL> getAcl() { return acl; }
        internal void setAcl(List<org.apache.zookeeper.data.ACL> m_) { acl = m_; }

        public int getFlags() { return flags; }
        internal void setFlags(int m_) { flags = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeString(path, "path");
            a_.writeBuffer(data, "data");
            {
                a_.startVector(acl, "acl");
                if (acl != null)
                {
                    foreach (var e1 in acl) a_.writeRecord(e1, "e1");
                }
            }
            a_.writeInt(flags, "flags");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            path = a_.readString("path");
            data = a_.readBuffer("data");
            {
                Index vidx1 = a_.startVector("acl");
                if (vidx1 != null)
                {
                    var tmpLst = new List<org.apache.zookeeper.data.ACL>();
                    for (; !vidx1.done(); vidx1.incr())
                    {
                        org.apache.zookeeper.data.ACL e1;
                        e1 = new org.apache.zookeeper.data.ACL();
                        a_.readRecord(e1, "e1");
                        tmpLst.Add(e1);
                    }
                    acl = tmpLst;
                }
            }
            flags = a_.readInt("flags");
        }
    }
}
