// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class ErrorResponse : Record
    {
        private int err;
        public ErrorResponse() { }
        public ErrorResponse(int err)
        {
            this.err = err;
        }
        public int getErr() { return err; }
        internal void setErr(int m_) { err = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(err, "err");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            err = a_.readInt("err");
        }
    }
}
