// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class ExistsRequest : Record
    {
        private string path;
        private bool watch;
        public ExistsRequest() { }
        public ExistsRequest(string path, bool watch)
        {
            this.path = path;
            this.watch = watch;
        }
        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        public bool getWatch() { return watch; }
        internal void setWatch(bool m_) { watch = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeString(path, "path");
            a_.writeBool(watch, "watch");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            path = a_.readString("path");
            watch = a_.readBool("watch");
        }
    }
}
