// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class GetACLRequest : Record
    {
        private string path;
        public GetACLRequest() { }
        public GetACLRequest(string path)
        {
            this.path = path;
        }
        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeString(path, "path");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            path = a_.readString("path");
        }
    }
}
