// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class GetChildren2Response : Record
    {
        private List<string> children;
        private org.apache.zookeeper.data.Stat stat;
        public GetChildren2Response() { }
        public GetChildren2Response(List<string> children, org.apache.zookeeper.data.Stat stat)
        {
            this.children = children;
            this.stat = stat;
        }
        public List<string> getChildren() { return children; }
        internal void setChildren(List<string> m_) { children = m_; }

        public org.apache.zookeeper.data.Stat getStat() { return stat; }
        internal void setStat(org.apache.zookeeper.data.Stat m_) { stat = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            {
                a_.startVector(children, "children");
                if (children != null)
                {
                    foreach (var e1 in children) a_.writeString(e1, e1);
                }
            }
            a_.writeRecord(stat, "stat");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            {
                Index vidx1 = a_.startVector("children");
                if (vidx1 != null)
                {
                    var tmpLst = new List<string>();
                    for (; !vidx1.done(); vidx1.incr())
                    {
                        string e1;
                        e1 = a_.readString("e1");
                        tmpLst.Add(e1);
                    }
                    children = tmpLst;
                }
            }
            stat = new org.apache.zookeeper.data.Stat();
            a_.readRecord(stat, "stat");
        }
    }
}
