// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class GetDataResponse : Record
    {
        private byte[] data;
        private org.apache.zookeeper.data.Stat stat;
        public GetDataResponse() { }
        public GetDataResponse(byte[] data, org.apache.zookeeper.data.Stat stat)
        {
            this.data = data;
            this.stat = stat;
        }
        public byte[] getData() { return data; }
        internal void setData(byte[] m_) { data = m_; }

        public org.apache.zookeeper.data.Stat getStat() { return stat; }
        internal void setStat(org.apache.zookeeper.data.Stat m_) { stat = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeBuffer(data, "data");
            a_.writeRecord(stat, "stat");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            data = a_.readBuffer("data");
            stat = new org.apache.zookeeper.data.Stat();
            a_.readRecord(stat, "stat");
        }
    }
}
