// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class MultiHeader : Record
    {
        private int type;
        private bool done;
        private int err;
        public MultiHeader() { }
        public MultiHeader(int type, bool done, int err)
        {
            this.type = type;
            this.done = done;
            this.err = err;
        }
        public int get_Type() { return type; }
        internal void set_Type(int m_) { type = m_; }

        public bool getDone() { return done; }
        internal void setDone(bool m_) { done = m_; }

        public int getErr() { return err; }
        internal void setErr(int m_) { err = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(type, "type");
            a_.writeBool(done, "done");
            a_.writeInt(err, "err");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            type = a_.readInt("type");
            done = a_.readBool("done");
            err = a_.readInt("err");
        }
    }
}
