// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class RequestHeader : Record
    {
        private int xid;
        private int type;
        public RequestHeader() { }
        public RequestHeader(int xid, int type)
        {
            this.xid = xid;
            this.type = type;
        }
        public int getXid() { return xid; }
        internal void setXid(int m_) { xid = m_; }

        public int get_Type() { return type; }
        internal void set_Type(int m_) { type = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(xid, "xid");
            a_.writeInt(type, "type");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            xid = a_.readInt("xid");
            type = a_.readInt("type");
        }
    }
}
