// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class SetACLResponse : Record
    {
        private org.apache.zookeeper.data.Stat stat;
        public SetACLResponse() { }
        public SetACLResponse(org.apache.zookeeper.data.Stat stat)
        {
            this.stat = stat;
        }
        public org.apache.zookeeper.data.Stat getStat() { return stat; }
        internal void setStat(org.apache.zookeeper.data.Stat m_) { stat = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeRecord(stat, "stat");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            stat = new org.apache.zookeeper.data.Stat();
            a_.readRecord(stat, "stat");
        }
    }
}
