// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class SetDataRequest : Record
    {
        private string path;
        private byte[] data;
        private int version;
        public SetDataRequest() { }
        public SetDataRequest(string path, byte[] data, int version)
        {
            this.path = path;
            this.data = data;
            this.version = version;
        }
        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        public byte[] getData() { return data; }
        internal void setData(byte[] m_) { data = m_; }

        public int getVersion() { return version; }
        internal void setVersion(int m_) { version = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeString(path, "path");
            a_.writeBuffer(data, "data");
            a_.writeInt(version, "version");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            path = a_.readString("path");
            data = a_.readBuffer("data");
            version = a_.readInt("version");
        }
    }
}
