// note: decompiled from ZooKeeperNetEx source
// File generated by hadoop record compiler. Do not edit.

#pragma warning disable

using System.Collections.Generic;
using org.apache.jute;

namespace org.apache.zookeeper.proto
{
    internal class WatcherEvent : Record
    {
        private int type;
        private int state;
        private string path;
        public WatcherEvent() { }
        public WatcherEvent(int type, int state, string path)
        {
            this.type = type;
            this.state = state;
            this.path = path;
        }
        public int get_Type() { return type; }
        internal void set_Type(int m_) { type = m_; }

        public int getState() { return state; }
        internal void setState(int m_) { state = m_; }

        public string getPath() { return path; }
        internal void setPath(string m_) { path = m_; }

        void Record.serialize(OutputArchive a_, string tag)
        {
            a_.writeInt(type, "type");
            a_.writeInt(state, "state");
            a_.writeString(path, "path");
        }
        void Record.deserialize(InputArchive a_, string tag)
        {
            type = a_.readInt("type");
            state = a_.readInt("state");
            path = a_.readString("path");
        }
    }
}
